### ISSUE TITLE
Choosing the right Template

### ISSUE THREAD

**Issue by malvarez1234** [NandosUK/malariathon#14]
With the designs we're looking at the right Gatsby template that can give us a headstart. The intent is to match the designs as much as possible but to quickly work with Sarah towards making sure that we meed half-way between the available functionality and the design.

**Comment by oshentonaf** [comment]
I have put int https://bulma.io/ as CSS frame work, so hopefully a minimal amount of custom SCSS will have to be written, it is on the /feature/FE-set-up branch

**Comment by malvarez1234** [comment]
Main template and look and feel is there.
